### ISSUE TITLE
Monthly awards

### ISSUE THREAD

**Issue by bobhenl** [BenCodez/VotingPlugin#1008]
**Versions**
Snapshot 6.0 (I think 2./3. dev build)

**Relevant information**
`[00:00:27] [Craft Scheduler Thread - 3808/WARN]: [VotingPlugin] Detected a reward file MonthlyAwards_2_Rewards edited when it should be edited where directly defined, overriding`
What this means please?

**Comment by BenCodez** [comment]
Means you edited a reward in the rewards folder that is defined in the specialrewards.yml (or the files differed)

**Comment by bobhenl** [comment]
Wait, I have this in config:
```
EnableMonthlyAwards: true
# Rewards to give
MonthlyAwards:
  # Position. 1 is first in top voter, 2 is second, etc...
  # Using 1-10 will reward players in first to tenth place with the same reward
  1:
    Rewards:
      Messages:
        Player: '&c&lHlasování &f» &eUmístil ses na &f1. &emístě v &f%TopVoter%&e!'
  2:
    Rewards:
      Messages:
        Player: '&c&lHlasování &f» &eUmístil ses na &f2. &emístě v &f%TopVoter%&e!'

```
and this in special rewards:
```
EnableMonthlyAwards: true
MonthlyAwards:
  '1':
    Rewards:
      Messages:
        Player: '&c&lHlasování &f» &eMěl jsi &fnejvíce &ehlasů za minulý &fměsíc&e. Získáváš za to &f4000€&e, &f5 diamantů&e, &f2 smaragdy&e, &f16 železa&e, &fknížku účinnost 5&e, &f2 očarovaná zlatá jablka&e, &fknížku oprava&e, &f32 XP lahví&e a &f10% &eslevu do obchodu.'
      Commands:
      - 'give %player% iron_ingot 16'
      - 'give %player% experience_bottle 32'
      - 'give %player% diamond 5'
      - 'give %player% emerald 2'
      - 'give %player% enchantedbook 1 e Efficiency:5'
      - 'give %player% enchantedbook 1 e Mending:5'
      - 'give %player% enchantedgoldenapple 2'
      Money: 5000
  '2':
    Rewards:
      Messages:
      Messages:
        Player: '&c&lHlasování &f» &eMěl jsi &fjako 2. nejvíce &ehlasů za minulý &fměsíc&e. Získáváš za to &f3000€&e, &f4 diamanty&e, &f2 smaragdy&e, &f12 železa&e, &fknížku účinnost 4&e, &f2 očarovaná zlatá jablka&e, &fknížku oprava&e, &f24 XP lahví&e a &f7.5% &eslevu do obchodu.'
      Commands:
      - 'give %player% iron_ingot 12'
      - 'give %player% experience_bottle 24'
      - 'give %player% diamond 4'
      - 'give %player% emerald 2'
      - 'give %player% enchantedbook 1 e Efficiency:4'
      - 'give %player% enchantedbook 1 e Mending:1'
      - 'give %player% enchantedgoldenapple 2'
      Money: 3000
  '3':
    Rewards:
      Messages:
      Messages:
        Player: '&c&lHlasování &f» &eMěl jsi &fjako 3. nejvíce &ehlasů za minulý &fměsíc&e. Získáváš za to &f3000€&e, &f3 diamanty&e, &f1 smaragd&e, &f8 železa&e, &fknížku účinnost 4&e, &f1 očarované zlatá jablko&e, &fknížku nerozbitnost 3&e, &f16 XP lahví&e a &f5% &eslevu do obchodu.'
      Commands:
      - 'give %player% iron_ingot 8'
      - 'give %player% experience_bottle 16'
      - 'give %player% diamond 3'
      - 'give %player% emerald 1'
      - 'give %player% enchantedbook 1 e Efficiency:4'
      - 'give %player% enchantedbook 1 e Unbreaking:3'
      - 'give %player% enchantedgoldenapple 1'
      Money: 2000
```
