### ISSUE TITLE
FirstVote reward

### ISSUE THREAD

**Issue by junebug12851** [BenCodez/VotingPlugin#1013]
I'm really trying to understand this, lets start really simple. This is the default config for first-time voters

```yml
FirstVote: 
  Messages:
    Player: '&aYou voted for your first time!'
```

Now what on earth do I do to add in a reward. There's literally nothing anywhere that I can find in the default configs or the wiki. Even taking guesswork gets me lost

For example, I have no idea what `VoteParty`, but under it is a section as such
```yml
  Rewards: 
    Commands:
    - say %player%
    Items:
      DIAMOND:
        Material: 'DIAMOND'
        Amount: 1
```

So I can maybe infer from this that I'm supposed to do this

```yml
FirstVote: 
  Messages:
    Player: '&aYou voted for your first time!'
  Items:
    DIAMOND:
      Material: 'DIAMOND'
      Amount: 1
```

But that's a shot in the dark, regardless even if that's how you do it we have another problem. There's reward files in a rewards folder and those files are never once referenced anywhere at all so while it says to use the name of the file without extension, I'm completely left in the dark as what to do with that information.

This is what comes to mind

```yml
FirstVote: 
  Messages:
    Player: '&aYou voted for your first time!'
  Rewards: [ ExampleBasic]
```

I'm completely guessing at this point, I'm utterly lost, can you help me figure this out, how do I attach a reward file to FirstVote?
