### ISSUE TITLE
Choice Rewards Race Condition

### ISSUE THREAD

**Issue by delbertina** [BenCodez/VotingPlugin#1020]
**Versions**
VP 6.0 dev build # 45
Paper 1.16.3

**Describe the bug**
When executing the `/av givereward [name] [player]` command too fast for the same choice reward file to a player it can encounter a race condition.

For the sake of reproducibility, I made a reward file that executes the command fast instead of directly listing the reward. This is because I originally found this bug using a different plugin that executes a varied number of times.

**To Reproduce**
1. Use the reward files below
2. `/av GiveReward RewardFile1 [playername]`
3. Go to `/vote choices`
4. Click thru to 'claim' and notice how there's not 7

**Screenshots/Configs**
RewardFile1
```
Rewards:
  Commands:
    Console:
    - 'av givereward RewardFile2 %player%'
    - 'av givereward RewardFile2 %player%'
    - 'av givereward RewardFile2 %player%'
    - 'av givereward RewardFile2 %player%'
    - 'av givereward RewardFile2 %player%'
    - 'av givereward RewardFile2 %player%'
    - 'av givereward RewardFile2 %player%'
```

RewardFile2
```
EnableChoices: true
DisplayItem:
  Name: '&c1'
  Material: REDSTONE_BLOCK
  Amount: 1
  Lore:
  - Claim
Choices:
  Choice-1:
    DisplayItem:
      Name: '&aClick Here'
      Material: GUNPOWDER
      Lore:
      - Click to claim
      Amount: 1
    Rewards:
      Messages:
        Player: '&2+1 &8added to your account'
DirectlyDefinedReward: true
```
