### ISSUE TITLE
Vote party - do players get reward when they vote, are offline while vote boom is reached and connect after?

### ISSUE THREAD

**Issue by bobhenl** [BenCodez/VotingPlugin#1028]
**Versions**
Plugin version and spigot version
6.0 ver

**Context**
Hi, I'm a little bit confused, when do players get reward from vote boom. If their votes are counted to vote boom, but they're offline, will they get reward after connecting to the server, if the boom where they had votes was reached?

And also, when I accept offline votes and players votes are announced in chat after their join, are these votes count to voteboom after their join or instantly when they vote? Cause if it's when they vote, then if they don't need to be online for vote boom, then they're automatically in almost every vote boom, if they voted atleast once and were offline.

**Comment by BenCodez** [comment]
You can set it to not reward when offline. It's configurable. Also when you say vote boom I assume your talking vote party.

**Comment by bobhenl** [comment]
Yeah, and where can I disable for offline please?

**Comment by BenCodez** [comment]
Either disable GiveAllPlayers or add RewardType: ONLINE in the rewards

**Comment by bobhenl** [comment]
GiveAllPlayers is disabled:
  GiveAllPlayers: false

And RewardType: ONLINE, do you mean it like this?
```
  Rewards:
    Commands:
    - 'cmi ctellraw %player% <T>&c&lHlasování &f» &eZa účast v &fhlasovacím boomu &ejsi dostal &f400 peněz&e,
      &f2 hlas. body &ea &fklíč &eod truhly &c&lHlasovací &fboom&e!</T>'
    - cmi kit HlasovaniBoom %player%
    - av User %player% AddPoints 2
    Money: 400
    RewardType: ONLINE
```
And now it will give JUST Online players, even if they voted and were offline they won't get reward?

**Comment by BenCodez** [comment]
So give all players to true and set UserVotesRequired to 1?

**Comment by bobhenl** [comment]
I mean online players who voted, so I don't need to set all players to true and required votes to 1, no?  Now I have:
```
VoteParty:
  Enabled: true
  VotesRequired: 30
  GiveAllPlayers: false
  ResetEachDay: true
  ResetMonthly: false
  ResetExtraVotesMonthly: false
  CountFakeVotes: true
  UserVotesRequired: 1
  Broadcast: '&cHlasovací boom!'
  Commands: []
  Rewards:
    Commands:
    - 'cmi ctellraw %player% <T>&c&lHlasování &f» &eZa účast v &fhlasovacím boomu &ejsi dostal &f400 peněz&e,
      &f2 hlas. body &ea &fklíč &eod truhly &c&lHlasovací &fboom&e!</T>'
    - cmi kit HlasovaniBoom %player%
    - av User %player% AddPoints 2
    Money: 400
    RewardType: ONLINE
```
