### ISSUE TITLE
VoteShop trade items instead of costing voting points

### ISSUE THREAD

**Issue by FireController1847** [BenCodez/VotingPlugin#1072]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
I would love the ability to set the cost of an item on the voteshop to not be the cost of your vote points, however an item that you receive each time you vote. For example, if I give players a "special diamond" and encourage them to keep it, they could trade said "special diamond" for, say, a netherite ingot, rather than using it on diamond armor or whatnot.

My proposed solution is to allow an item to be described for the cost instead of just a points. I'm not entirely sure how to implement this, but I was thinking something along the lines of, if it's a list of items, ensure the player has the items, comparing both the name and lore as well (to allow for special items). I was thinking something like this:
```yml
cost:
- SpecialDiamond:
    Material: DIAMOND
    Data: 0
    Amount: 64
    Name: 'My Special Diamond'
    Lore:
    - 'Collect enough of these and you can trade it for something special!'
```
The example above would cost 64 diamonds matching the name "My Special Diamond" with the lore "Collect enough of these and you can trade it for something special!"

Of course, if this is not the route you'd like to take, it's always an option to add JavaScript support and require the return of a true or false, which would allow the flexibility of the above and some

**Describe alternatives you've considered**
Possibly another plugin used for trading, but this plugin is so comprehensive, I think it'd add to the value of the shop considerably.

**Additional context**
N/A

**Comment by BenCodez** [comment]
I like the idea, just not sure if it would fit within the plugin that well. I think bossshop might have this ability already?

**Comment by FireController1847** [comment]
I'll take a look at BossHopPro, it seems to have what I need. Thanks!

**Comment by FireController1847** [comment]
Alright, using BossHopPro I have managed to achieve what I am looking for. Thank you!
```yml
ShopName: VoteShop
DisplayName: Vote Shop
Command: voteshop
signs:
  text: '[VoteShop]'
  NeedPermissionToCreateSign: true
shop:
  NetheriteIngot:
    MenuItem:
    - type:NETHERITE_INGOT
    - amount:1
    - name:&aConsistent Voter
    - lore:Click me to trade 64 voting diamonds!
    - enchantment:UNBREAKING#3
    RewardType: COMMAND
    Reward:
    - 'av givereward %player% LegendaryReward'
    PriceType: ITEM
    Price:
    - - type:DIAMOND
      - amount:64
      - name:&a8 Vote Champion
      - 'lore1:Legends say that if you collect enough of these,'
      - 'lore2:you can trade them for something special'
      - enchantment:UNBREAKING#2
    Message: ''
    InventoryLocation: 1
    ExtraPermission: ''
```
