### ISSUE TITLE
Different message when player joins and there is spam with "offline votes"

### ISSUE THREAD

**Issue by bobhenl** [BenCodez/VotingPlugin#1076]
**Is your feature request related to a problem? Please describe.**
Not really, there is just a little spam when player who voted offline joins server. Some players then ask why he voted so many times at once.
![image](https://user-images.githubusercontent.com/18662086/102789159-06a36080-43a4-11eb-82b3-6c1b72f2168e.png)

**Describe the solution you'd like**
I suggest different message (string) for votes that are sent when player voted as offline, so we could add there that he voted offline to message.

**Describe alternatives you've considered**
Way to send only 1 message.

**Additional context**
Also support for NuVotifier offline voting.

**Comment by BenCodez** [comment]
What bungee setup are you using?
https://github.com/BenCodez/VotingPlugin/wiki/Bungeecoord-Setups

**Comment by BenCodez** [comment]
There is also an option BroadcastWhenOnline to only broadcast when online.

You can also disable that broadcast and add a broadcast within the rewards, which you could set a different message for online/offline

**Comment by bobhenl** [comment]
For now I'm using:
Forwarding to each server (independent storage) without running on Bungee

BroadcastWhenOnline  -> and yea, but then there's spam

You can also disable that broadcast and add a broadcast within the rewards, which you could set a different message for online/offline -> This is prob. almost what I want, but how could I do this? But the best would be if it's announced on player's join but offline votes with different messages

**Comment by BenCodez** [comment]
Rewards/OnlineMessage.yml:

    RewardType: ONLINE
    Messages:
       Broadcast: 'Broadcast'

Rewards/OfflineMessage.yml:

    RewardType: OFFLINE
    Messages:
       Broadcast: 'Broadcast'

just list both of those rewards under everysitereward (or anysitereward to only have 1 message on offlines votes)

**Comment by bobhenl** [comment]
And could I set there count how many times he voted? I mean placeholder for offline votes?

**Comment by BenCodez** [comment]
There isn't a way to do that currently, not sure if that's possible

**Comment by bobhenl** [comment]
And just question, I'm now a little bit confused, when to use folder of Rewards and when normal specialrewards and votesites rewards? I have same things in in specialrewards and even in rewardsa nd monthly rewards, so i'm a little bit confused why and what to keep up to date. But as I see, specialized reward is more up to date.

**Comment by BenCodez** [comment]
Keep the votesites and specialrewards up to date, they convert to reward files when needed.

**Comment by bobhenl** [comment]
yeah, but my reward file (vote party one) is old and there aren't changes I made few days ago in specializedreward. That's weird.

So, when I wanna do this 

> just list both of those rewards under everysitereward (or anysitereward to only have 1 message on offlines votes)

How I will do it?
```
  Czech-Craft_eu:
    Enabled: true
    ServiceSite: Czech-Craft.eu
    VoteURL: https://czech-craft.eu/server/mcreunion/vote/
    VoteDelay: 2
    Item:
      Material: GRASS
      Amount: 1
    Rewards:
      Money: 100
      Commands:
      - cmi kit HlasovaniCzechCraft %player%
      Messages:
        Player: '&c&lHlasování &f» &eZa hlasování na &f%ServiceSite%&e jsi dostal
          &f100 peněz, 1 hlas. bod, 5 lektvarů očarování, 5 jablek, sliz a klíč&e.
          Nezapomeň na &c/denniodmena&e + &c/vylepseni&e.'
```
What should be listed there?
This?
    Rewards:
     - OnlineMessage
     -  OfflineMessages
Or?
