### ISSUE TITLE
Bugs and forcevote all feature request

### ISSUE THREAD

**Issue by LogGits** [BenCodez/VotingPlugin#1154]
**Is your feature request related to a problem? Please describe.**
`VotingPlugin 6.3`
`Paper 1.16.5 build 644`
Yes and I am not sure where to start so i'll mention all the odd occurrences that lead up to this issue.

1. Not even sure this caused but going to mention, during #1152 i used `/av backgroundupdate`. There was no noticeable affects (it didn't give me the votes) so i had to update via ur api changes.
2. After that, a player came on and their daily vote total didn't reset for some reason (we have 4 votesites). As a result the [player had 5 votes](https://gyazo.com/3e403f09fcb47fdafbeeff920b1952ae). As 4 votes = 1 key, the player was receiving a key for every vote (received 2 vote keys, with 2 left waiting for 24hrs) while the `VoteSites.yml` looked like this:
```yaml
VoteSites:
  PlanetMinecraft_com:
    Enabled: true
    ServiceSite: PlanetMinecraft.com
    VoteURL: VoteURL
    VoteDelay: 24
    Rewards:
    - EverySiteReward
  PlanetMinecraft:
    com:
      ServiceSite: PlanetMinecraft.com
  Minecraft-MP_com:
    Enabled: true
    ServiceSite: Minecraft-MP.com
    VoteURL: VoteURL
    VoteDelay: 24
    Rewards:
    - EverySiteReward
  Minecraft-MP:
    com:
      ServiceSite: Minecraft-MP.com
  Topg_org:
    Enabled: true
    ServiceSite: Topg.org
    VoteURL: VoteURL
    VoteDelay: 24
    WaitUntilVoteDelay: false
    Rewards:
    - EverySiteReward
  Topg:
    org:
      ServiceSite: Topg.org
  MCSL_com:
    Enabled: true
    ServiceSite: MCSL
    VoteURL: VoteURL
    VoteDelay: 24
    Rewards:
    - EverySiteReward
  MCSL:
    com:
      ServiceSite: MCSL
```
3. To prevent this from happening again, I added `WaitUntilVoteDelay: true` to all links.
4. A restarted the server and started getting reports saying "I voted 24 hrs after my previous vote and nothing registered". They lost all

Players were nolonger able to receive vote rewards and lost streaks. Inorder to rectify this issue I decided to use the `/av user [user] forcevote [votename]` however it was taking ages to write the command manually for each votelink. So idk this is both a feature req and 2 bug reports?

**Describe the solution you'd like**
`/av user [user] forcevote All` whereby it triggers a vote on all votelinks that are enabled.

**Describe alternatives you've considered**
I manually typed the forcevote for all users that seemed to be affected by the issue.

*If you need any more info, please let me know and I'd be happy to provide it to you though here or discord (depending on the nature of the request).*

Thanks in advance.
