### ISSUE TITLE
Monthly Award

### ISSUE THREAD

**Issue by x1p** [BenCodez/VotingPlugin#1163]
**Versions**
VotingPlugin v6.3.2
Purpur 1.16.5 (paper fork)

**Describe the bug**
A player reported this message
![Screenshot_2021-06-03 095131](https://user-images.githubusercontent.com/28690790/120608611-ab48c480-c451-11eb-88e9-be0d1d538c95.png)
This is remarkable because I have everything not needed turned off or translated. Or so I thought. In search of my bad I found this line in the config:
```yaml
  # Msg on top voter award, will only send message if that place has a reward set
  # %place% = place - 1,2,3,etc
  TopVoterAwardMsg: '&aYou came in %place% in top voters of the month! Here is an award!
```
But this couldn't be the cause since the last part of this sentence is missing in the screenshot. So I couldn't find it right away and eventually turned of this:
```yaml
LoadTopVoter:
  AllTime: true
  Monthly: false #<-- This was turned on because it might come handy for staff to be able to see monthly top votes
  Weekly: false
  Daily: false
```
Until I stumbled upon the SpecialRewards file. Here is the exact line I was searching for. But it's turned off!
```yaml
EnableMonthlyAwards: false
# Rewards to give
MonthlyAwards:
  # Position. 1 is first in top voter, 2 is second, etc...
  # Using 1-10 will reward players in first to tenth place with the same reward
  1:
    Rewards:
      Messages:
        Player: '&aYou came in first place in %TopVoter%!'
  2:
    Rewards:
      Messages:
        Player: '&aYou came in second place in %TopVoter%!'
```
So the question would be: how is it possible that players see this line, while turned off?
I now have monthly turned off completely I guess. But isn't it strange?

**To Reproduce**
I did not try to reproduce because I can't wait a month to pass in order to test.

**Expected behavior**
When `EnableMonthlyAwards: false` is turned off, I would think that the MonthlyAwards are not executed.

**Screenshots/Configs**
See above

**Additional context**
