### ISSUE TITLE
Vote site get's re-enabled if vote comes through.

### ISSUE THREAD

**Issue by andrewkm** [BenCodez/VotingPlugin#1175]
When disabling a voting site:

```
  MCTools_org:
    Enabled: false
    ServiceSite: MCTools.org
    VoteURL: VoteURL
    VoteDelay: 24
    DisplayItem:
      Material: GRASS
      Amount: 1
    Rewards:
      Messages:
        Player: '&aThanks for voting on %ServiceSite%!'
```

And voting on it again (in the above scenario, using the service again)...
Configuration auto changes to true:

```
  MCTools_org:
    Enabled: true
    ServiceSite: MCTools.org
    VoteURL: VoteURL
    VoteDelay: 24
    DisplayItem:
      Material: GRASS
      Amount: 1
    Rewards:
      Messages:
        Player: '&aThanks for voting on %ServiceSite%!'
```

Is this intended?
