### ISSUE TITLE
Vote reminders on few lines.

### ISSUE THREAD

**Issue by ghost** [BenCodez/VotingPlugin#195]
Hello. Is there any way to set up vote reminders using more than one line? So for example, I used this in the config to get this in the game:
```
Messages:
  Player:
  - lin1
  - lin2
```
http://i.imgur.com/YEIS1PA.png

**Comment by BenCodez** [comment]
Try one line with %NewLine% in between the lines. Not sure if that's the
correct placeholder for it, but it's something like that

**Comment by ghost** [comment]
Thanks a lot. By the way, is there any way to disable the /vote command so my other plugin would display the text I need?
(edited)

**Comment by ghost** [comment]
Because whenever I change the text in the /vote section, it just continues to display the default "vote for our server" message, ever after I reload and restart the server.

**Comment by BenCodez** [comment]
There should be an option somewhere, can't remember what it was

On May 20, 2017 4:34 PM, "AndGK" <notifications@github.com> wrote:

Because whenever I change the text in the /vote section, it just continues
to display the default "vote for our server" message, ever after I reload
and restart the server.

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/Ben12345rocks/VotingPlugin/issues/195#issuecomment-302897153>,
or mute the thread

**Comment by ghost** [comment]
Welp, I can't find it...

**Comment by BenCodez** [comment]
Think this is it:
https://github.com/Ben12345rocks/VotingPlugin/blob/master/VotingPlugin/Resources/Config.yml#L90

**Comment by ghost** [comment]
I already have that on false, otherwise, it would just show GUI but it just shows default text.

**Comment by BenCodez** [comment]
Just went to double check and that's the correct option, might require a
restart

**Comment by ghost** [comment]
As I said above, 

> Because whenever I change the text in the /vote section, it just continues to display the default "vote for our server" message, ever after I reload and restart the server.

**Comment by BenCodez** [comment]
Set autoinputsites to false, and make sure it's a list in the text section.

**Comment by ghost** [comment]
That's what I had:
```
Commands:
    # Format for /vote
    # %num% = the number of the site, for a numbered list
    # %url% = site URL
    vote: 
      Text:
      - ' Help Auria grow by voting and in return,'
      - ' we will reward you with some sweets! :)'
      - ''
      - ''
      - ''
      
      # If you want to want to use the feature below where the plugin will
      # automaticly list the sites then set the message in the text above
      AutoInputSites: false
```
