### ISSUE TITLE
Question: how to reset milestone rewards after the month ends?

### ISSUE THREAD

**Issue by ghost** [BenCodez/VotingPlugin#197]
So I have set it up as follows:

```
 MileStones:
  '5':
    Enabled: true
    Rewards:
      Commands:
        Console:
         - 'kit rookie %player%'
      Messages:
        Player: '&aYou have hit the &b#%milestone%&a milestone. Here is your reward! &7(/rewards)'
    ResetMonthly: true
  '10':
    Enabled: true
    Rewards:
      Commands:
        Console:
         - 'eco give %player% 10000'
         - 'give %player% tnt 32'
         - 'give %player% obsidian 32'
      Messages:
        Player: '&aYou have hit the &b#%milestone%&a milestone. Here is your reward! &7(/rewards)'
    ResetMonthly: true
```

But today, when the month ended and a player had hit one of the previous milestones last month, he receives previous milestones with it. So if the player hit the 10 votes milestone last month, and voted one more time this month, he would receive the 5 and 10 votes milestone. How can I make them reset, so he would need to hit the milestone again?
