### ISSUE TITLE
VoteStreak Feature Request: Reward also for multiples of a defined value

### ISSUE THREAD

**Issue by Platinteufel** [BenCodez/VotingPlugin#281]
I want to give my users a reward for **voting 7 days in a row**.
So I configured it this way:

```
VoteStreak:
  # Valid options: Day, Week, Month
  Day:
    # Number of days in a row
    # Each day requires one vote
    '7':
      # Enabled or not
      Enabled: true
      # Rewards to give
      Rewards:
        Money: 10
        Messages:
          Player: "&aYou've voted 7 days in a row!"
          Broadcast: "&a%Player% has voted 7 days in a row and recieves extra $10!" 
```

The problem is that they should get the reward **every time they voted 7 days in a row**, so at
7, 14, 21, 28, 35, 42 [...]. 
As it could be a bit complex to create an entry for every multiple of 7, maybe it would make sense to have an option for it? What do you think, is it a possible way?

Thank you in advance!
