### ISSUE TITLE
CMI custom alias commands not working.

### ISSUE THREAD

**Issue by 0xC1A551C** [BenCodez/VotingPlugin#350]
In my rewards.yml file I am trying to make a custom command from the CMI plugin run when a vote is executed. For reference I am running a 1.8 server at the moment.

Commands:
  Console: []
  Player:
  - 'cistest'
  - 'broadcast hi'

For example, the 'cistest' command /cistest broadcasts a test message in chat. I have added the broadcast command with "hi" to verify the player commands work (they do).

When a vote is executed I get errors which I am assuming is linked to this problem.

`07.02 09:54:05 [Server] WARN java.lang.ClassNotFoundException: net.minecraft.server.v1_8_R3.ChatMessageType 07.02 09:54:05 [Server] WARN at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:92) 07.02 09:54:05 [Server] WARN at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:87) 07.02 09:54:05 [Server] WARN at java.lang.ClassLoader.loadClass(ClassLoader.java:424) 07.02 09:54:05 [Server] WARN at java.lang.ClassLoader.loadClass(ClassLoader.java:357) 07.02 09:54:05 [Server] WARN at java.lang.Class.forName0(Native Method) 07.02 09:54:05 [Server] WARN at java.lang.Class.forName(Class.java:264) 07.02 09:54:05 [Server] WARN at com.Ben12345rocks.VotingPlugin.AdvancedCore.NMSManager.NMSManager.getNMSClass(NMSManager.java:209) 07.02 09:54:05 [Server] WARN at com.Ben12345rocks.VotingPlugin.AdvancedCore.Util.Effects.ActionBar.sendActionBar(ActionBar.java:134) 07.02 09:54:05 [Server] WARN at com.Ben12345rocks.VotingPlugin.AdvancedCore.Util.Effects.ActionBar.sendActionBar(ActionBar.java:162) 07.02 09:54:05 [Server] WARN at com.Ben12345rocks.VotingPlugin.AdvancedCore.Util.Effects.ActionBar.send(ActionBar.java:88) 07.02 09:54:05 [Server] WARN at com.Ben12345rocks.VotingPlugin.AdvancedCore.Objects.User.sendActionBar(User.java:748) 07.02 09:54:05 [Server] WARN at com.Ben12345rocks.VotingPlugin.AdvancedCore.Objects.Reward.sendActionBar(Reward.java:1586) 07.02 09:54:05 [Server] WARN at com.Ben12345rocks.VotingPlugin.AdvancedCore.Objects.Reward.giveRewardUser(Reward.java:1188) 07.02 09:54:05 [Server] WARN at com.Ben12345rocks.VotingPlugin.AdvancedCore.Objects.Reward.giveRewardReward(Reward.java:1149) 07.02 09:54:05 [Server] WARN at com.Ben12345rocks.VotingPlugin.AdvancedCore.Objects.Reward.giveReward(Reward.java:1123) 07.02 09:54:05 [Server] WARN at com.Ben12345rocks.VotingPlugin.AdvancedCore.Objects.RewardHandler$5.run(RewardHandler.java:286) 07.02 09:54:05 [Server] WARN at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:59) 07.02 09:54:05 [Server] WARN at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53) 07.02 09:54:05 [Server] WARN at org.github.paperspigot.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:23) 07.02 09:54:05 [Server] WARN at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) 07.02 09:54:05 [Server] WARN at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) 07.02 09:54:05 [Server] WARN at java.lang.Thread.run(Thread.java:748) 07.02 09:54:05 [Server] WARN java.lang.NoSuchMethodException: net.minecraft.server.v1_8_R3.PacketPlayOutChat.<init>(net.minecraft.server.v1_8_R3.IChatBaseComponent, null) 07.02 09:54:05 [Server] WARN at java.lang.Class.getConstructor0(Class.java:3082) 07.02 09:54:05 [Server] WARN at java.lang.Class.getConstructor(Class.java:1825) 07.02 09:54:05 [Server] WARN at com.Ben12345rocks.VotingPlugin.AdvancedCore.Util.Effects.ActionBar.sendActionBar(ActionBar.java:132) 07.02 09:54:07 [Multicraft] Skipped 14 lines due to rate limit (30/s) 07.02 09:54:07 [Server] WARN java.lang.ClassNotFoundException: net.minecraft.server.v1_8_R3.ChatMessageType 07.02 09:54:07 [Server] WARN at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:92) 07.02 09:54:07 [Server] WARN at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:87) 07.02 09:54:07 [Server] WARN at java.lang.ClassLoader.loadClass(ClassLoader.java:424) 07.02 09:54:07 [Server] WARN at java.lang.ClassLoader.loadClass(ClassLoader.java:357) 07.02 09:54:07 [Server] WARN at java.lang.Class.forName0(Native Method) 07.02 09:54:07 [Server] WARN at java.lang.Class.forName(Class.java:264) 07.02 09:54:07 [Server] WARN at com.Ben12345rocks.VotingPlugin.AdvancedCore.NMSManager.NMSManager.getNMSClass(NMSManager.java:209) 07.02 09:54:07 [Server] WARN at com.Ben12345rocks.VotingPlugin.AdvancedCore.Util.Effects.ActionBar.sendActionBar(ActionBar.java:134) 07.02 09:54:07 [Server] WARN at com.Ben12345rocks.VotingPlugin.AdvancedCore.Util.Effects.ActionBar$1.run(ActionBar.java:170) 07.02 09:54:07 [Server] WARN at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:59) 07.02 09:54:07 [Server] WARN at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:352) 07.02 09:54:07 [Server] WARN at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:783) 07.02 09:54:07 [Server] WARN at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378) 07.02 09:54:07 [Server] WARN at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:713) 07.02 09:54:07 [Server] WARN at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:616) 07.02 09:54:07 [Server] WARN at java.lang.Thread.run(Thread.java:748) 07.02 09:54:07 [Server] WARN java.lang.NoSuchMethodException: net.minecraft.server.v1_8_R3.PacketPlayOutChat.<init>(net.minecraft.server.v1_8_R3.IChatBaseComponent, null) 07.02 09:54:07 [Server] WARN at java.lang.Class.getConstructor0(Class.java:3082) 07.02 09:54:07 [Server] WARN at java.lang.Class.getConstructor(Class.java:1825) 07.02 09:54:07 [Server] WARN at com.Ben12345rocks.VotingPlugin.AdvancedCore.Util.Effects.ActionBar.sendActionBar(ActionBar.java:132) 07.02 09:54:07 [Server] WARN at com.Ben12345rocks.VotingPlugin.AdvancedCore.Util.Effects.ActionBar$1.run(ActionBar.java:170) 07.02 09:54:07 [Server] WARN at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:59) 07.02 09:54:07 [Server] WARN at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:352) 07.02 09:54:07 [Server] WARN at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:783) 07.02 09:54:07 [Server] WARN at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378) 07.02 09:54:07 [Server] WARN at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:713) 07.02 09:54:07 [Server] WARN at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:616) 07.02 09:54:07 [Server] WARN at java.lang.Thread.run(Thread.java:748)`

**Comment by BenCodez** [comment]
Don't think action bars work in 1.8

**Comment by 0xC1A551C** [comment]
Disabling the actionbar which works in 1.8 on other plugins does remove the error. There are a few other things (not sure where to submit).

- Still can't run custom commands as a command from either the rewards file or voteparty.

```
  UserVotesRequired: 0
  # Broadcast when vote party reached
  Broadcast: '&8[&aE&5T&8] &c&lVote party will begin in 30 seconds! Type &a/dp'
  # List of commands to execute, these only execute once.
  Commands: 
  - cistest
  - cistest
  - cistest
  - 'cistest'

```
- Cannot broadcast multiple line messages when a player has voted

**Comment by BenCodez** [comment]
Can you run other commands?

Add a %NewLine%


On Feb 8, 2018 1:24 AM, "0xC1A551C" <notifications@github.com> wrote:

Disabling the actionbar which works in 1.8 on other plugins does remove the
error. There are a few other htings (not sure where to submit).

   - Still can't run custom commands in the rewardsfile.yml like command
   alias's in CMI.
   - Cannot broadcast multiple line messages when a player has voted

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/Ben12345rocks/VotingPlugin/issues/350#issuecomment-364014870>,
or mute the thread

**Comment by 0xC1A551C** [comment]
I am able to run other commands such as: smite username, ect

It just seems like any custom commands created in CMI don't work for some reason - the custom commands do work in-game with /customcommandname 


I've also tried adding Console and Player under the commands section, but that doesn't work for either regular commands or custom commands even though it is documented here: https://github.com/Ben12345rocks/VotingPlugin/wiki/Basic-Rewards 

```
VoteParty:
  # Wether or not vote party is enabled
  Enabled: true
  # Number of votes required to give rewards
  VotesRequired: 1
  # If true, players who did not vote to reach the votes required will 
  # recieve the reward
  GiveAllPlayers: false
  # If true, the vote count will reset each day
  ResetEachDay: false
  # Reset at the end of the month
  ResetMonthly: false
  # Count votes from /av vote?
  CountFakeVotes: true
  # Number of user votes that apply to vote party total the user needs to get rewards
  UserVotesRequired: 0
  # Broadcast when vote party reached
  Broadcast: '&8[&aE&5T&8] &c&lVote party will begin in 30 seconds! Type &a/dp'
  # List of commands to execute, these only execute once.
  Commands: 
      Console:
        - 'smite playerusername1'
      Player:
        - 'smite playerusername1'
```

Do you have discord? Would be great to talk 1:1 to solve this problem since I have tried a lot of different ways to execute the CMI commands.

**Comment by BenCodez** [comment]
I think its the way CMI handles commands. Not much I can do.

    Commands:
      Player:
      - 'test'

You had an extra 2 spaces. Try that ^

I made a discord server, but haven't really used it:
https://discord.gg/N9jU8zq

**Comment by 0xC1A551C** [comment]
Thanks

I tried adding the code, but it still doesn't seem to work - not sure why. I am reloading the plugin with /av reload after every change.

```
VoteParty:
  # Wether or not vote party is enabled
  Enabled: true
  # Number of votes required to give rewards
  VotesRequired: 1
  # If true, players who did not vote to reach the votes required will 
  # recieve the reward
  GiveAllPlayers: false
  # If true, the vote count will reset each day
  ResetEachDay: false
  # Reset at the end of the month
  ResetMonthly: false
  # Count votes from /av vote?
  CountFakeVotes: true
  # Number of user votes that apply to vote party total the user needs to get rewards
  UserVotesRequired: 0
  # Broadcast when vote party reached
  Broadcast: '&8[&aE&5T&8] &c&lVote party will begin in 30 seconds! Type &a/dp'
  # List of commands to execute, these only execute once.
  Commands:
    Player:
    - 'smite username'
    - 'dp'
```
