### ISSUE TITLE
Cumulative rewards

### ISSUE THREAD

**Issue by kunwon1** [BenCodez/VotingPlugin#382]
I have this section in my config, the rewards seem to be being given too often, i'm wondering if i'm misunderstanding something about how Cumulative vote rewards work. I want to rank people up after various numbers of votes, like give them a promotion at 3 votes, then another promotion at 7 votes, then another promotion at 11 votes..
```
Cumulative:
  # Number of votes required
  # Allows multiple cumulative rewards
  # Number be be around ' (E.g. '1')
  # Can have multiple listed here
  '3':
    Enabled: true
    VotesInSameDay: false
    VotesInSameWeek: false
    Rewards:
      Messages:
        Player: '&aYou got promoted! You are now &7(Upstanding)&r! Thank you very much for voting <3'
        Console: 'say %player% voted and is now &7(Upstanding)&r!'
      Commands:
      - 'pex promote %player% Voter'
  '7':
    Enabled: true
    VotesInSameDay: false
    VotesInSameWeek: false
    Rewards:
      Messages:
        Player: '&aYou got promoted! You are now a &7(Squire)&r! Thank you very much for voting <3'
      Commands:
      - 'pex promote %player% Voter'
      - 'say %player% voted and is now a &7(Squire)&r!'
  '11':
    Enabled: true
    VotesInSameDay: false
    VotesInSameWeek: false
    Rewards:
      Messages:
        Player: '&aYou got promoted! You are now a &5(Knight)&r! Thank you very much for voting <3'
      Commands:
      - 'pex promote %player% Voter'
      - 'say %player% voted and is now a &5(Knight)&r!'
```
