### ISSUE TITLE
Offline vote party issue

### ISSUE THREAD

**Issue by LogGits** [BenCodez/VotingPlugin#444]
Players are reporting not getting rewards from the vote party. Most of them were offline but i think some were online. Is there something wrong with my setup (i did a test and while im online i get a reward):
```yaml
VoteParty:
  # Wether or not vote party is enabled
  Enabled: true
  # Number of votes required to give rewards
  VotesRequired: 60
  # Increase the amount of votes required on each vote party reached
  #IncreaseVotesRquired: 10
  # If true, players who did not vote to reach the votes required will 
  # recieve the reward
  GiveAllPlayers: false
  # If true, the vote count will reset each day
  ResetEachDay: false
  # Reset at the end of the month
  ResetMonthly: false
  # Count votes from /av vote?
  CountFakeVotes: true
  # Number of user votes that apply to vote party total the user needs to get rewards
  UserVotesRequired: 3
  # Broadcast when vote party reached
  Broadcast: '[Party] The vote party has been reached. Goto /spawn to use your keys!'
  # List of commands to execute, these only execute once.
  # %player% does not work here
  Commands: []
  # Rewards to give
  Rewards: 
    Commands:
    - cr give to %player% Party 1
    ActionBar:
      Message: 'Thank you for voting, use the keys at /spawn!'
```
