### ISSUE TITLE
Timesince variable

### ISSUE THREAD

**Issue by x1p** [BenCodez/VotingPlugin#448]
I've noticed that the `%timesince%` variable uses its own English description for the time format.
This is despite the translation which I have translated into my own language. Default config setting:
```
  TimeFomrats:
    Day: 'Day'
    Days: 'Days'
    Hour: 'Hour'
    Hours: 'Hours'
    Minute: 'Minute'
    Minutes: 'Minutes'
    Second: 'Second'
    Seconds: 'Seconds'
```
Note that the "TimeFomrats" is misspelled.

Q: how is timesince formatted and is this editable?

Using VotingPlugin 5.16.1 (stable from spigotmc)
