### ISSUE TITLE
Permissions issue with tabcomplete

### ISSUE THREAD

**Issue by LogGits** [BenCodez/VotingPlugin#451]
Players who dont have access to specific commands are able to tab complete them in 1.13.
This is because the plugin.yml isn't setup properly. An example of a plugin.yml setup that prevents tabcomplete of commands that a player doesn't have access to is:
```yaml
commands:
  start:
    description: hub of important commands.
    aliases: info
    permission: test.start

permissions:
  test.start:
    description: give access to /start
    default: op
```
