### ISSUE TITLE
Per world cumulative rewards?

### ISSUE THREAD

**Issue by Numpty-Clodpole** [BenCodez/VotingPlugin#487]
**Second edit:**

We've decided to go ahead and allow voting on all worlds, so you can disregard this. I'm closing it.

_____

Hello, I'm having a problem where players are able to vote and receive rewards in worlds that they aren't supposed to. Skyblock, for example. I used the example shown in "ExampleAdvanced.yml" to use the whitelisted worlds function. This is what I have in each of the specific cumulative reward files:

```YAML
# Directly defined reward file. ANY EDITS HERE CAN GET OVERRIDDEN!
Commands:
- minecraft:give %player% minecraft:totem_of_undying 1
- minecraft:give %player% minecraft:diamond 1
Messages:
  Player: '&aThank you for voting 18 times this week; here is a Totem of Undying.'
DirectlyDefinedReward: true
Worlds:
- 'world1'
- 'world1_the_end'
- 'world1_nether
- 'Ether'
```

Am I misunderstanding how the `Worlds:` argument works? I'd like to have voting enabled *only* within those listed worlds.

Oh, I guess I should edit this and mention that the server is running the latest Spigot 1.13.2, and the VotingPlugin is updated to `5.17.3`. If any other info is needed, please let me know.
