### ISSUE TITLE
Question/request voting

### ISSUE THREAD

**Issue by LogGits** [BenCodez/VotingPlugin#493]
I have a setup on my server that goes like this:
1 vote = 1 item
3 votes = diamond + entered into vote party
4 votes = key

if a player votes on 3 how much time can go by before their final vote to make it 4 votes? (meaning when will it get reset and act like they have voted once) Also is this affected by restarts? our server restarts at 7am every day. Would this reset a players daily vote count?

Also with my same system I am having this issue with votestreaks:
```yaml
  Requirement:
    # Require certain percentage of votes
    UsePercentage: true
    # Percentage requirements of votes
    # 50 = %50
    Day: 60
    Week: 60
    Month: 60
```
it appears when a player voted on 3 websites it didnt increase her votestreak instead it set it back to 0. 3/4 votes is 75%, what could have caused this and is it possible to fix.
Here is a look at her voting + servertime:
https://gyazo.com/25f79e7faa691b144909621dccbd5dfc

I am on votingplugin 5.17.4 with paper 1.13.2 build 507
