### ISSUE TITLE
support with weekly votes

### ISSUE THREAD

**Issue by Castiella** [BenCodez/VotingPlugin#515]
Hi
, I'm trying to set a thing where players get a key for voting on every website each week. However when i try to set it up it just breaks the plugin so i must be doing something wrong. Please could you advise me?
```
 '42':
    Enabled: true
    # Wether or not votes must be made in same day/week
    # Useful if you want to require a certain number of voting sites to be voted on
    # for a daily/weekly reward instead of all of them
    VotesInSameDay: false
    VotesInSameWeek: true
    Rewards:
        Commands:
    - crates give p perkcrate 1 %player%
    - say &6 %player% voted &7on every site, everyday and received a &6Perk Crate Key! 
      Messages:
        Player: '&aYou voted on every site, every day this week!'
```
