### ISSUE TITLE
Server Running Spigot 1.8.8 Throws A ClassNotFoundException Error Upon Login

### ISSUE THREAD

**Issue by ghost** [BenCodez/VotingPlugin#516]
## Hello Devs!

So I'm currently running a server using Spigot 1.8.8. I have downloaded, and redownloded the JAR file version of 5.13.6 as per the documentation for servers running 1.12 or lower. Every time a player logs in it throws and error in the console of ClassNotFoundException.

### Here is the Pastebin of the error.
https://pastebin.com/r03A4h27

**NOTE: Some information has been redacted to protect the privacy of the user.**

Not really sure what to do here for this error. It seems as though the plugin is still working because whenever someone votes, the correct reward is still given. There is no other errors in console during the voting process. I have also tried running the server without any other plugins installed except for NuVotifier and VotingPlugin. This has not resolved the issue either.

### List of plugins on the server currently
https://imgur.com/a/AHs6vbL

**Comment by BenCodez** [comment]
Disable any action bars.

**Comment by ghost** [comment]
I don't currently have any Action Bars. I only use TAB for the tab menu and LiteBoard for the menu on the side. No other plugins mess with the players HUD.

**Comment by BenCodez** [comment]
Check the vote reminding, there might be one from the default config

**Comment by ghost** [comment]
```
Rewards:
    Messages:
      Player: '&8&l[&6InfernoVote&8] &3» &cRemember to vote! Use /vote to cast your vote today!'
    Title:
      Enabled: false
      Title: '&cRemember to vote!'
      SubTitle: '&aType /vote to vote!'
      FadeIn: 10
      ShowTime: 50
      FadeOut: 10
    ActionBar:
      Message: '&cRemember to vote'
      Delay: 30
```

Do I set the delay to -1 in order to disable? There isn't an Enabled option under ActionBar. Should there be?
