### ISSUE TITLE
I think i've set up rewards files and VoteSites.yml wrong

### ISSUE THREAD

**Issue by KaarNij** [BenCodez/VotingPlugin#556]
Hi hoping u could tell me what I've done wrong tried looking online for awhile now, i remember at 1 point /vote worked, prob until i changed the 'votesites.yml' and 'ExampleBasic.yml' in rewards folder which i renamed 'Voterewards', haven't really changed any other files except maybe in main config

[Voterewards.zip](https://github.com/Ben12345rocks/VotingPlugin/files/3316561/Voterewards.zip)
[VoteSites.zip](https://github.com/Ben12345rocks/VotingPlugin/files/3316562/VoteSites.zip)

**Comment by BenCodez** [comment]
Rewards: 'Votingrewards'
      Commands:
        console:
        - 'give %player% diamond 2'
        - 'eco give %player% 40'
        Player: 
        - '&a%player%, You voted, Thanks for Voting for BoxVerse!'
        - '&a%player%, You just earned 2 Diamond and $40'
        - '&a%player%, You  now have a total of $%money%!'

You can't do that. Either the reward file or the directly defined reward.
https://github.com/Ben12345rocks/AdvancedCore/wiki/Rewards

**Comment by KaarNij** [comment]
so something like this would work if i deleted the voterewards.yml i made and changed it back to this?

```
    Rewards:
      Commands:
        console:
        - 'give %player% diamond 2'
        - 'eco give %player% 40'
        Player: 
        - '&a%player%, You voted, Thanks for Voting for BoxVerse!'
        - '&a%player%, You just earned 2 Diamond and $40'
        - '&a%player%, You  now have a total of $%money%!'
```
because when i go in the game and type /vote it doesnt know the command??
