### ISSUE TITLE
Not an issue - me again

### ISSUE THREAD

**Issue by JoshJJones** [BenCodez/VotingPlugin#607]
Sorry to make ANOTHER one, I should really check before I close it.

```
VoteSites:
  PlanetMinecraft_com:
    Enabled: true
    ServiceSite: PlanetMinecraft.com
    VoteURL: https://www.planetminecraft.com/server/mgn-factions-1-13-2-w-1-14-support-factions-economy-crates-kits-and-more/vote/
    VoteDelay: 24
    Item:
      Material: DIAMOND
      Amount: 1
    Rewards:
      AdvancedPriority:
      # Similar to priority, but no need to have to use reward files
      # Add requirements under each reward
      # Will go in order from list here and try to run each of the following rewards...
      # This name can be anything, but they need to be different
      Reward1:
        RequirePermission: true
        Permission: 'AdvancedCore.Reward.DonorDouble'
        # Any other requirement here
        # If any requirement fails, the next will be attempted
        Commands:
        - eco give %player% 25000
        - crate give to %player% Vote 1
        - eco give %player% 25000
        - crate give to %player% Vote 1
      Fallback:
        Commands:
        - eco give %player% 25000
        - crate give to %player% Vote 1
```
That's my current config, its repeated for each site from Rewards: down... 
After doing this players stopped recieving rewards, including the fall back.
