### ISSUE TITLE
Bug with VoteParty on newest version

### ISSUE THREAD

**Issue by DrakePork** [BenCodez/VotingPlugin#621]
After I installed the newest version of the plugin whenever voteparty happens it does successfully go through and execute the commands and messages, however it put these errors in console:

When voteparty was reached with votes
[Pastebin](https://pastebin.com/2vF9W0pV)

When I reloaded the plugin
[Pastebin2](https://pastebin.com/SDvue2fy)

When I forced voteparty
[Pastebin3](https://pastebin.com/vEqDvV5z)

This is what I have at VoteParty in config.yml:
```
VoteParty:
  Enabled: true
  VotesRequired: 50
  GiveAllPlayers: true
  ResetEachDay: false
  ResetMonthly: false
  CountFakeVotes: true
  UserVotesRequired: 0
  Broadcast: '&f[&2&lVote&f] &9The Vote Party amount has been reached. Therefore, everyone online gets a &5&lMythic &7&lCrate &b&lKey'
  Commands:
  - cc giveall P mythic 1
  Rewards: 
    Commands: []
    Items: []
```

It also made a VoteParty_Rewards.yml file in Rewards folder which has this in it:

```
# Directly defined reward file. ANY EDITS HERE CAN GET OVERRIDDEN!
Commands: []
Items: []
DirectlyDefinedReward: true
```
