### ISSUE TITLE
Question: Can i add commands to be executed if a user buys from the VoteShop?

### ISSUE THREAD

**Issue by SgtChrisCross** [BenCodez/VotingPlugin#631]
Question: Can i add commands to be executed if a user buys from the VoteShop?

I use items that can only be generated via command - special keys to open chests.

I tried this and it didn't work:
It don't work at all, it does not execute a command and the item i get from the rewards don't work for the chests.

```
    Rewards:
      Items:
        UngewöhnlicherSchlüssel:
          Material: 'TRIPWIRE_HOOK'
          Amount: 1
          Commands:
          - 'cc give p Ungewöhnlich 1 %player%'
          Name: '&8&lUngewöhnlicher &r&fSchlüssel'
          Lore:
          - '&7Ein Schlüssel für eine Lootbox.'
          - '&7Löse den Schüssel am Spawn ein.'
          - ''
          - '&8&lUngewöhnlich'
```
