### ISSUE TITLE
Votesite order

### ISSUE THREAD

**Issue by x1p** [BenCodez/VotingPlugin#655]
What determines the order of the vote sites in all GUI's where the sites are presented?

For some reason, the order of the vote sites is reversed. So I tried to change order in the Votesites.yml but they are still reversed

What can I do to force the order?

**Comment by BenCodez** [comment]
It's based on priority (each site has a priority setting)

**Comment by x1p** [comment]
I waited for the reboot, but I don't see any difference. Did I miss something?

VoteSites.yml
```
VoteSites:
  VoteSite1:
    Enabled: true
    Priority: 1
    ServiceSite: whatever.com
    VoteURL: https://website.com/vote1
    VoteDelay: 12
    WaitUntilVoteDelay: false
    VoteDelayDaily: false
    ForceOffline: false
    Item:
      Material: GRASS
      Amount: 1
    Rewards: []
  VoteSite2:
    Enabled: true
    Priority: 2
    ServiceSite: whatever.com
    VoteURL: https://website.com/vote2
    VoteDelay: 24
    WaitUntilVoteDelay: false
    VoteDelayDaily: false
    ForceOffline: false
    Item:
      Material: GRASS
      Amount: 1
    Rewards: []
```
