### ISSUE TITLE
Question about bungee settings

### ISSUE THREAD

**Issue by zeronerve** [BenCodez/VotingPlugin#672]
Hi. In the bungeeconfig.yml file, I need to better understand this section ...

```
# Bungee communication, Add this to each spigot server
BungeeServer:
  Host: '0.0.0.0'
  Port: 12345
```

Since this config resides on the bungee server, I'm confused about what host and port should be included here. I'm assuming the host should be the WAN address of the bungee server. But should be port also be the port that bungee itself is listening on or another port specifically for voting?

I'm using the latest version of VotingPLugin and the latest version of Paper 1.14.4
