### ISSUE TITLE
How to configure Votifier to give random keys (for crate rewards)?

### ISSUE THREAD

**Issue by FourNineRugz** [BenCodez/VotingPlugin#673]
I couldn't quite figure it out. But I was wondering how I would make something like this work.

```
VoteSites:
  PlanetMinecraft:
    Enabled: true
    Name: Planet Minecraft
    ServiceSite: PlanetMinecraft.com
    VoteURL: https://www.planetminecraft.com/server/mc-bucketry-net-smp-lands-economic-pvp/vote/
    VoteDelay: 24
    WaitUntilVoteDelay: false
    VoteDelayDaily: false
    ForceOffline: false
    Item:
      Material: DIAMOND
      Amount: 1
    Rewards:
AdvancedPriority:
  # Similar to priority, but no need to have to use reward files
  # Add requirements under each reward
  # Will go in order from list here and try to run each of the following rewards...
  # This name can be anything, but they need to be different
  Reward1:
    Chance: 50
    # Any other requirement here
    # If any requirement fails, the next will be attempted
    Commands:
    - 'cc give p Mythical 1 %player%'
  Reward2:
    Chance: 20
    Commands:
    - 'cc give p Antique 1 %player%'
  # Fallback, 100% chance
  Fallback:
    Messages:
      Player: 'You got unlucky'
```
