### ISSUE TITLE
AllSites question

### ISSUE THREAD

**Issue by LogGits** [BenCodez/VotingPlugin#786]
**Versions**
5.21.1 VotingPlugin, AdvancedCore 2.20.9, Paper 1.15.2 build 226

**Context**
Is there a way to set a max daily voting. We have 4 vote links but one of them allows voting every 12 hours. This means `AllSites` rewards get given twice. Is there a way to prevent voting above the amount of vote above the amount of sites?

E.g. with:
```yaml
AllSites: 
  ActionBar:
    Message: '&6Thank you for voting!'
    Delay: 30
  Commands:
    - cr give to %player% Vote 1
```
The player will get 2 vote crate keys.

Should i just do cumulative votes as 4 for the vote key? And if so, is this reset daily?

**Comment by BenCodez** [comment]
You can make it wait on votedelay and set that to 24 hours.

**Comment by LogGits** [comment]
So by setting up the 12 hour one to have a 24 hour delay it wont let the person get rewarded twice for AllSites?

**Comment by LogGits** [comment]
I just realised that i already have the votesites set to votedelay 24:
```yaml
  Topg_org:
    Enabled: true
    ServiceSite: Topg.org
    VoteURL: VoteURL
    VoteDelay: 24
    Rewards:
    - EverySiteReward
  Topg:
    org:
      ServiceSite: Topg.org
```
Any ideas?
