### ISSUE TITLE
Issue's with VoteSites.yml

### ISSUE THREAD

**Issue by Gintamier** [BenCodez/VotingPlugin#799]
I have my VoteSites.yml set up like this:

```yml
VoteSites:
  Site1:
    Enabled: true
    Name: 'Minecraft Server List'
    Priority: 5
    ServiceSite: 'minecraft-server-list.com'
    VoteURL: 'https://minecraft-server-list.com/server/459584/vote'
    VoteDelay: 24
    WaitUntilVoteDelay: false
    VoteDelayDaily: false
    ForceOffline: false
    Item:
      Material: 'DIAMOND'
      Amount: 1
    Rewards:
      Commands:
        Console:
        - 'ccrate give physical vote 1 %player%'
        - 'cheque %player% 2500'
        - 'broadcast &b%player% &7has voted and received &b1 Vote Key, and $2500'
      Messages:
        Player: 'You voted'
  Site2:
    Enabled: true
    Name: 'Minecraft Servers'
    Priority: 1
    ServiceSite: 'minecraftservers.org'
    VoteURL: 'https://minecraftservers.org/vote/584134'
    VoteDelay: 24
    WaitUntilVoteDelay: false
    VoteDelayDaily: false
    ForceOffline: false
    Item:
      Material: 'DIAMOND'
      Amount: 1
    Rewards:
      Commands:
        Console:
        - 'ccrate give physical vote 1 %player%'
        - 'cheque %player% 2500'
        - 'broadcast &b%player% &7has voted and received &b1 Vote Key, and $2500'
      Messages:
        Player: 'You voted'
  Site3:
    Enabled: true
    Name: 'Minecraft MP'
    Priority: 1
    ServiceSite: 'minecraft-mp.com'
    VoteURL: 'https://minecraft-mp.com/server/247930/vote/'
    VoteDelay: 24
    WaitUntilVoteDelay: false
    VoteDelayDaily: false
    ForceOffline: false
    Item:
      Material: 'DIAMOND'
      Amount: 1
    Rewards:
      Commands:
        Console:
        - 'ccrate give physical vote 1 %player%'
        - 'cheque %player% 2500'
        - 'broadcast &b%player% &7has voted and received &b1 Vote Key, and $2500'
      Messages:
        Player: 'You voted'
  Site4:
    Enabled: true
    Name: 'Minecraft Buzz'
    Priority: 1
    ServiceSite: 'minecraft.buzz'
    VoteURL: 'https://minecraft.buzz/server/375'
    VoteDelay: 24
    WaitUntilVoteDelay: false
    VoteDelayDaily: false
    ForceOffline: false
    Item:
      Material: 'DIAMOND'
      Amount: 1
    Rewards:
      Commands:
        Console:
        - 'ccrate give physical vote 1 %player%'
        - 'cheque %player% 2500'
        - 'broadcast &b%player% &7has voted and received &b1 Vote Key, and $2500'
      Messages:
        Player: 'You voted'
  Site5:
    Enabled: true
    Name: 'Top G'
    Priority: 1
    ServiceSite: 'topg.org'
    VoteURL: 'https://topg.org/Minecraft/in-605392'
    VoteDelay: 24
    WaitUntilVoteDelay: false
    VoteDelayDaily: false
    ForceOffline: false
    Item:
      Material: 'DIAMOND'
      Amount: 1
    Rewards:
      Commands:
        Console:
        - 'ccrate give physical vote 1 %player%'
        - 'cheque %player% 2500'
        - 'broadcast &b%player% &7has voted and received &b1 Vote Key, and $2500'
      Messages:
        Player: 'You voted'
  Site6:
    Enabled: true
    Name: 'Minecraft List'
    Priority: 1
    ServiceSite: 'minecraftlist.org'
    VoteURL: 'https://minecraftlist.org/vote/16916'
    VoteDelay: 24
    WaitUntilVoteDelay: false
    VoteDelayDaily: false
    ForceOffline: false
    Item:
      Material: 'DIAMOND'
      Amount: 1
    Rewards:
      Commands:
        Console:
        - 'ccrate give physical vote 1 %player%'
        - 'cheque %player% 2500'
        - 'broadcast &b%player% &7has voted and received &b1 Vote Key, and $2500'
      Messages:
        Player: 'You voted'
EverySiteReward: []

```

And no issue loading it in.
For some reason, When someone votes, a Random site MSCL
Gets inserted in there, And all the symbols for commands and stuff > ' ' < 
Those dudes, get removed, and resulting that no one gets their stuff until I either manually give it to them, Or set the code up again and save etc, So they can get it.
I have no clue why this keeps happening, Or how to fix it.

**Comment by BenCodez** [comment]
It will generate a votesite if no votesite with the correct service site is found. Check console log for the service site.

**Comment by Gintamier** [comment]
Is there a command I can run to check the service sites?

**Comment by Gintamier** [comment]
> It will generate a votesite if no votesite with the correct service site is found. Check console log for the service site.

Is there a command that can be run in console to check the sites?

**Comment by Gintamier** [comment]
There is 1 site error, But I set it up exactly as all the others.. It's this one that is having issues
```yml
  Site1:
    Enabled: true
    Name: 'Minecraft Server List'
    Priority: 1
    ServiceSite: 'minecraft-server-list.com'
    VoteURL: 'https://minecraft-server-list.com/server/459584/vote'
    VoteDelay: 24
    WaitUntilVoteDelay: false
    VoteDelayDaily: false
    ForceOffline: false
    Item:
      Material: 'DIAMOND'
      Amount: 1
    Rewards:
      Commands:
        Console:
        - 'ccrate give physical vote 1 %player%'
        - 'give money %player% 2500'
        - 'broadcast &b%player% &7has voted and received &b1 Vote Key, and $2500'
      Messages:
        Player: 'You voted'
```
