### ISSUE TITLE
How do I give a reward for every vote, different rewards for each rank?

### ISSUE THREAD

**Issue by vastolf** [BenCodez/VotingPlugin#824]
**Versions**
Latest plugin & Paper-Spigot (new server)

**Relevant information**
Configs that relate to the issue in a pastebin.

**Context**
I am switching from SuperBVote. SuperBVote allows me to give a reward for each individual vote that a player makes. I would like to retain this functionality. Here's a full idea of what I want:

- **Every time** a player votes, **they should instantly receive a reward** (server should run commands I define)
- **The commands that are run for the Reward should depend on the player's rank** so that I can give different ranks different rewards

I'm having a really hard time figuring out where I could possibly define something like this in the config. I've read the documentation extensively but there aren't really any examples that seem to do what I want (I may be mistaken)

Could you point me in the direction of which area of Config I'd have to edit (do I edit the Config.yml, if so where in the Config.yml). And how to define a rewards structure that works as I've described. Thank you so much for your time! Really appreciate it.

**Comment by BenCodez** [comment]
In the default votesites.yml, there is a example of advanced priority with chance, this will give the first reward under advanced priority, the same can be done with permissions instead of chance.

If that's not enough info let me know I can send an example of it.

**Comment by vastolf** [comment]
Mine does not have this example, it must've been edited out. Do I have to do things on a vote-site by vote-site basis? I just want every vote from every site to trigger a reward, and a different reward based on rank. I would appreciate the example for sure, thank you so much for the quick response!

**Comment by vastolf** [comment]
@Ben12345rocks

**Comment by BenCodez** [comment]
You can either go site by site or use the everysitereward (bottom of votesites.yml)

https://github.com/Ben12345rocks/VotingPlugin/blob/master/VotingPlugin/Resources/VoteSites.yml#L82

There is the example, hope that helps.

**Comment by vastolf** [comment]
So assuming I have some LuckPerms groups defined called "Voter" and "Member", I can use the permissions from those groups like this?:
```
# Reward for any site
# Similar to AnySiteReward
# This requires the site to be configured in order to get the reward.
EverySiteReward: 
    Rewards:
        Commands:
        - 'say hello'
        # Advanced example
        # 50% chance for reward1, if reward1 not given then 20% chance to get reward2, if reward2 not given then fallback
        AdvancedPriority:
            # Similar to priority, but no need to have to use reward files
            # Add requirements under each reward
            # Will go in order from list here and try to run each of the following rewards...
            # This name can be anything, but they need to be different
            Reward1:
            RequirePermission: true
            Permission: group.voter
            Messages:
                Player: 'You got first reward'
            Commands:
            - say %player%
            Reward2:
            RequirePermission: true
            Permission: group.member
            Messages:
                Player: 'You got second reward'
            Commands:
            - say %player% 2
            Fallback:
            Messages:
                Player: 'You got unlucky'
            Commands:
            - say %player% default
```
