### ISSUE TITLE
Question about Permissions and rewards.

### ISSUE THREAD

**Issue by dev-stan** [BenCodez/VotingPlugin#852]
I couldn't find any info about how to give a certain reward to a player group, for example, the default group would get one diamond per vote on a site and the group with a certain permission node would get 2 diamonds. How would I go about doing that?

**Comment by BenCodez** [comment]
Use permissions and advanced priority.  Example of advanced priority in default votesites.yml would work, just swap chance with perms.

**Comment by dev-stan** [comment]
Thank you, using the code below it worked perfectly!
```
TestSite:
    Enabled: false
    ServiceSite: TestSite
    VoteURL: VoteURL
    VoteDelay: 24
    Rewards:
      Commands:
      - msg stanleykun %player% has voted!
      AdvancedPriority:
        Reward1:
          RequirePermission: true
          Permission: 'vote.donor'
          Commands:
          - give %player% diamond 2
        Reward2:
          RequirePermission: false
          Commands:
          - give %player% diamond 1
```
