### ISSUE TITLE
Offline voting rewards when user log in when I have 2 servers on same mysql?

### ISSUE THREAD

**Issue by bobhenl** [BenCodez/VotingPlugin#856]
**Versions**
1.15.2 and 1.16.2 (two servers with same mysql)
Waterfall on 1.16.1
votingPlugin: 5.22

**Relevant information**
https://pastebin.com/btSUkdgL

**Context**
Hi, I tried to vote when I was offline and I didn't get reward on server when I logged in.... How could I make please when player will vote and wouldn't be online he will get reward when he log in on one of these two servers (just one of them)?

EDIT: Also noticed that when I vote when offline it shows me that I can vote on server....

**Comment by BenCodez** [comment]
You'll need to provide more info. Did you follow one of these setups?

https://github.com/Ben12345rocks/VotingPlugin/wiki/Bungeecoord-Setups

**Comment by bobhenl** [comment]
Yes, I followed. You already helped me once... VotingPlugin on bungee didn't work for me so I have to connect these servers via same Database. It works except this. What info exactly do you need? Isn't relevant information (config) enough?

**Comment by BenCodez** [comment]
I'm confused on exactly what the problem is.

**Comment by bobhenl** [comment]
When players vote and they aren't online.... they join server after voting, they won't get any reward.

**Comment by BenCodez** [comment]
Enable ForceOffline within the votesite? Configs from each server? Including votesites.yml?

**Comment by bobhenl** [comment]
The second (semi vanilla) server: https://pastebin.com/43akr8f7

PS: The first one was Survival.
```

Votesites are same, except rewards:
# 
# Reward for any site
# Similar to AnySiteReward
# This requires the site to be configured in order to get the reward.
VoteSites:
  Czech-Craft_eu:
    Enabled: true
    ServiceSite: Czech-Craft.eu
    VoteURL: https://czech-craft.eu/server/mcreunion/vote/
    VoteDelay: 2
    Item:
      Material: GRASS_BLOCK
      Amount: 1
    Rewards:
      Money: 100
      Commands:
      - 'tokenmanager add %player% 1'
      - cmi kit HlasovaniCzechCraft %player%
      Messages:
        Player: '&aDěkujeme za hlasování na %ServiceSite%! Dostal jsi 1 token, 5 lektvarů očarování, 10 uhlí a 5 pečených kotlet.'
  Craftlist_org:
    Enabled: true
    ServiceSite: Craftlist.org
    VoteURL: https://craftlist.org/mcreunion#vote
    VoteDelay: 20
    Item:
      Material: CRAFTING_TABLE
      Amount: 1
    Rewards:
      Money: 500
      Commands:
      - 'tokenmanager add %player% 4'
      - cmi kit HlasovaniCraftList %player%
      Messages:
        Player: '&aDěkujeme za hlasování na %ServiceSite%! Dostal jsi 4 tokeny, 30 lektvarů očarování, 30 uhlí a 15 pečených kotlet.'
EverySiteReward: []

```

PS: When I vote when I'm online it works... there's just problem with offline votes.
