### ISSUE TITLE
%VoteUrl% placeholder breaks JSON formatting

### ISSUE THREAD

**Issue by ChrisTaylor201** [BenCodez/VotingPlugin#860]
#### Versions
Server core – PaperMC 1.15.2 build 375
Plugin – 5.22

#### Describe the bug
If `%VoteUrl%` placeholder is used, JSON formatting will break, however if a URL is written directly, it won't happen. I'll show a few examples of what I mean.
```yml
# Let %VoteUrl% be `https://www.randomvotesite.org`.

# This breaks the JSON formatting.
URLText: 'You can vote for the server here [Text="here",url="%VoteUrl%"].'
# Output: `You can vote for the server here]".`

# This doesn't break the JSON formatting.
URLText: 'You can vote for the server here [Text="here",url="https://www.randomvotesite.org"].'
# Output: `You can vote for the server here.`
```
As you can see, in the first example the placeholder isn't parsed correctly which breaks the formatting, see the trailing `]"` char sequence.

#### How to reproduce
1. Set `%VoteUrl%` to a URL.
2. Check the issue mentioned above.

#### Expected behavior
The URL should be parsed correctly in the first example.
