### ISSUE TITLE
Add an option to disable skulls for the Today menu

### ISSUE THREAD

**Issue by ChrisTaylor201** [BenCodez/VotingPlugin#864]
#### Is your feature request related to a problem? Please describe.
As we discussed in the issue #859, loading skulls it's not an instant task and can't be.

#### Describe the solution you'd like.
The solution would be to add an option to disable skulls for the `Today` menu, same as with the `Top` one – something like this:
```yml
VoteToday:
  # …
  UseSkull: false
  PlayerItem:
    Material: 'PAPER'
```

#### Describe alternatives you've considered.
Maybe using the text output instead of the menu, but if there's a lot of votes, the menu is much clearer.
