### ISSUE TITLE
Experimenting with Socket setup

### ISSUE THREAD

**Issue by x1p** [BenCodez/VotingPlugin#909]
**Versions**
5.23 (build 533)

**Describe the bug**
I'm trying to experiment with the bungee setup, type: socket. The other settings didn't fitt my need.
When Performing `votingpluginbungee status`, only Test1 responds.
```
[15:43:29 INFO]: CONSOLE executed command: /votingpluginbungee status
[15:43:29 INFO]: Checking status, waiting for response, check console, only for socket method
[15:43:29 INFO]: Socket Sending: status
[15:43:29 INFO]: Socket Sending: status
[15:43:29 INFO]: Socket Receiving: StatusOkay%line%Test1
[15:43:29 INFO] [VotingPlugin]: Voting communicaton okay with Test1
```
All secret keys are the same
I wonder what the issue might be.

**Additional context**
Settings Bungee (Waterfall)
```
BungeeServer:
    Host: '0.0.0.0'
    Port: 41040
  
# Bungee communication, add each spigot server here
SpigotServers:
  Test1:
    Host: '172.18.0.1'
    Port: 41041
  Test2:
    Host: '172.18.0.1'
    Port: 40042
```
Settings Test1 (Paper)
```
Server: Test1

# Bungee communication, add bungee host/port here
BungeeServer:
  Host: '172.18.0.1'
  Port: 41040
  
# Bungee communication, add this to bungee server
SpigotServer:
  Host: '0.0.0.0'
  Port: 41041
```
Settings Test2 (Paper)
```
Server: Test2

# Bungee communication, add bungee host/port here
BungeeServer:
  Host: '172.18.0.1'
  Port: 41040
  
# Bungee communication, add this to bungee server
SpigotServer:
  Host: '0.0.0.0'
  Port: 41042
```
All servers run in containers (Pterodactyl). This complicates things a bit.
I assume listening should happen on `0.0.0.0` and sending should happen on `172.18.0.1`
