### ISSUE TITLE
Error When Using 1.16 UUID Format

### ISSUE THREAD

**Issue by delbertina** [BenCodez/VotingPlugin#910]
**Versions**
VotingPlugin: 5.23
Paper 1.16.1 Build # 136

**Describe the bug**
Commands seem to be converted to all lowercase at some point which messes up with the [new 1.16 UUID format](https://redd.it/hi4kws) because it needs the capital I. When doing the command thru console it works as expected, when trying to run the command in a reward file is where it gives the error.
```
[21:28:53] [Server thread/INFO]: Invalid array type 'i'
[21:28:53] [Server thread/INFO]: ...wner:{id:[i;546599693,1610305534,-2084852774,-1937208781],properties:{textures:[{value:"eyj0zxh0dxjlcyi6eyjts0loijp7invybci6imh0dha6ly90zxh0dxjlcy5taw5ly3jhznqubmv0l3rlehr1cmuvy2uymzzlm2rlogmxnjrkmmrmzjfjnge0zwuzogrkzdzmn2ywyzbimdq3mmu2ywjlmtqymtm0mjk4otzhmzrlnyj9fx0="}]}}} 1<--[HERE]
```

**Screenshots/Configs**
Config.yml Snip
```
Shop:
  RandomDecoLight:
    Material: 'REDSTONE_LAMP'
    Data: 0
    Amount: 1
    Name: '&4Buy A Random Decor Light'
    # You can set skulls of the player using the following
    # Remove the # to enable
    #Skull: '%Player%'
    Lore:
    - '&c&lCost: &c24 Voting Points'
    - '&54 Different Types'
    - '&560 Total to Collect'
    # Number of voting points this cost
    Cost: 24 
    Rewards:
    - Random_DecorLights
    Slot: 1
```
Random_DecorLights.yml Snip
```
RandomCommand:
- 'minecraft:give %player% minecraft:player_head{display:{Name:"{\"text\":\"Decor Light :: Series D (red)\"}"},SkullOwner:{Id:[I;1732965436,-321830548,-1259364584,783200198],Properties:{textures:[{Value:"eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvODg0ZTkyNDg3YzY3NDk5OTViNzk3MzdiOGE5ZWI0YzQzOTU0Nzk3YTZkZDZjZDliNGVmY2UxN2NmNDc1ODQ2In19fQ=="}]}}} 1'
- 'minecraft:give %player% minecraft:player_head{display:{Name:"{\"text\":\"Decor Light :: Series D (blue)\"}"},SkullOwner:{Id:[I;348883231,901333997,-1440119131,-1434989664],Properties:{textures:[{Value:"eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNjdlMTFkYjhmMzkyNzI3YTFjNDU5ZWI1OTFkZDhhMGFhMzg2MWMyNzQ4N2UxMzg0YmIyMmY5MTU3M2JlNyJ9fX0="}]}}} 1'
- 'minecraft:give %player% minecraft:player_head{display:{Name:"{\"text\":\"Decor Light :: Series D (green)\"}"},SkullOwner:{Id:[I;-349305698,1432571383,-1098244983,305822113],Properties:{textures:[{Value:"eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNWU0ODYxNWRmNmI3ZGRmM2FkNDk1MDQxODc2ZDkxNjliZGM5ODNhM2ZhNjlhMmFjYTEwN2U4ZjI1MWY3Njg3In19fQ=="}]}}} 1'
```
