### ISSUE TITLE
VoteParty rewards all users

### ISSUE THREAD

**Issue by rmalca** [BenCodez/VotingPlugin#940]
**Versions**
Plugin version: 5.23.2
Spigot version: git-Paper-168 (MC: 1.16.2)

**Describe the bug**
I have seen something very strange today, I have configured the plugin to execute a certain command at 50 votes with VoteParty but what happened is that the command was executed for all players and the %VotingPlugin_VotePartyVotesNeeded% counter was reset to 50 for all players. The funny thing is that I found out from another user and when I entered the server the command was automatically executed with my username and my %VotingPlugin_VotePartyVotesNeeded% counter was reset.

**To Reproduce**
1. That a user x votes 50 times (configured in file SpecialRewards.yml VoteParty.VotesRequired)

**Expected behavior**
Only one user should claim the reward (run the command).

**Screenshots/Configs**
Console log:
```
[Fri, 4. Sep 2020 16:05:44 EST INFO] Gracias jere4455 por votar por HalfCraft.
[Fri, 4. Sep 2020 16:05:45 EST INFO] [HalfCraft] Given ZamuelLOL a crate key <-- Voto+ party reward (¿why?)
[Fri, 4. Sep 2020 16:05:45 EST INFO] [HalfCraft] Given Naguz a crate key <-- Voto+ party reward (¿why?)
[Fri, 4. Sep 2020 16:05:45 EST INFO] [HalfCraft] Given dieguito34 a crate key   <-- Voto+ party reward (¿why?)
[Fri, 4. Sep 2020 16:05:45 EST INFO] [HalfCraft] Given IOPKIENMAS a crate key <-- Voto+ party reward (¿why?)
[Fri, 4. Sep 2020 16:05:45 EST INFO] [HalfCraft] Given jere4455 a crate key       <-- Voto normal reward
[Fri, 4. Sep 2020 16:05:45 EST INFO] [HalfCraft] Given jere4455 a crate key       <-- Voto+ party reward
```

SpecialRewards.yml
```
# To disable reward set value to []
# or remove entirely
# Eg:
# FirstVote: [] (All in one line)
# Rewards will be given if there is a reward to give
# 
# First vote rewards
Cumulative:
  '50':
    Enabled: false
    VotesInSameDay: false
    VotesInSameWeek: false
    Rewards:
      Commands:
      - crate key %player% Voto+ 1
VoteParty:
  Enabled: true
  VotesRequired: 50
  GiveAllPlayers: false
  ResetEachDay: false
  ResetMonthly: false
  ResetExtraVotesMonthly: false
  CountFakeVotes: true
  UserVotesRequired: 0
  Broadcast: ''
  Commands: []
  Rewards:
    Commands:
    - crate key %player% Voto+ 1
ResetMilestonesMonthly: false
MileStones:
  '20':
    Enabled: false
    Rewards:
      Messages:
        Player: '&aYou got %milestone% milestone votes!'
VoteStreak:
  Day:
    '2':
      Enabled: false
      Rewards:
        Messages:
          Player: '&aYou voted for %Streak% %Type%''s in a row!'
  Week:
    '2':
      Enabled: false
      Rewards:
        Messages:
          Player: '&aYou voted for %Streak% %Type%''s in a row!'
  Month:
    '2':
      Enabled: false
      Rewards:
        Messages:
          Player: '&aYou voted for %Streak% %Type%''s in a row!'
  Requirement:
    UsePercentage: false
    Day: 50
    Week: 50
    Month: 50
EnableMonthlyAwards: false
MonthlyAwards:
  '1':
    Rewards:
      Messages:
        Player: '&aYou came in first place in %TopVoter%!'
  '2':
    Rewards:
      Messages:
        Player: '&aYou came in second place in %TopVoter%!'
EnableWeeklyAwards: false
WeeklyAwards:
  '1':
    Rewards:
      Messages:
        Player: '&aYou came in first place in %TopVoter%!'
  '2':
    Rewards:
      Messages:
        Player: '&aYou came in second place in %TopVoter%!'
EnableDailyRewards: false
DailyAwards:
  '1':
    Rewards:
      Messages:
        Player: '&aYou came in first place in %TopVoter%!'
  '2':
    Rewards:
      Messages:
        Player: '&aYou came in second place in %TopVoter%!'

```

**Additional context**
