### ISSUE TITLE
Cummulative placeholder

### ISSUE THREAD

**Issue by rmalca** [BenCodez/VotingPlugin#943]
**Is your feature request related to a problem? Please describe.**
I can't get how many votes a player has advanced towards his goal.

**Describe the solution you'd like**
It would be very useful to be able to obtain how many votes have accumulated in SpecialRewards.Cumulative in a placeholder.

**Describe alternatives you've considered**

**Additional context**
```
Cumulative:
  '50':
    Enabled: true
    VotesInSameDay: false
    VotesInSameWeek: false
    Rewards:
      Commands:
      - crate key %player% Voto+ 1
```
