### ISSUE TITLE
Non-recurring votestreak rewards.

### ISSUE THREAD

**Issue by LogGits** [BenCodez/VotingPlugin#964]
**Is your feature request related to a problem? Please describe.**
I am unable to set votestreaks rewards that aren't recurring.

**Describe the solution you'd like**
The option to make a votestreak reward only happens once the player reaches the votestreak number. e.g:
```yaml
VoteStreak:
  Day:
    '30':
      Enabled: true
      Recurring: false #This should determine if it happens every 30 days or only once the player hits 30 days.
      Rewards:
        Messages:
          Player: "&aYou voted for %Streak% %Type%'s in a row!"
```
